# Generated by Django 4.2.18 on 2025-02-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
